services:
  vue-nginx:
    image: ghcr.io/nrf24l01/polyhack-gopobeda/frontend-build:latest
    ports:
      - "8001:80"
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower-frontend
    restart: unless-stopped
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=300
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock